export const enum HtmlTags {
  FORM = 'form',
  INPUT = 'input',
  SELECT = 'select',
  LABEL = 'label',
  BUTTON = 'button',
  CONTAINER = 'div',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  SPAN = 'span',
  PARAGRAPH = 'p',
  LIST = 'ul',
  LIST_ITEM = 'li',
  FOOTER = 'footer',
  HEADER = 'header',
  MAIN = 'main',
  LINK = 'a',
}
